# ── Resolva o exercício aqui ──────────────────────────────────────────────



# Passo 6: cole o output do git log aqui como comentário
# git log:

# Passo 1: carregue o CSV

In [16]:
#PRIMEIRO LUGAR PRECISAMOS BAIXAR As BIBLIOTECA PANDAS e R PARA CONSEGUIR PUXAR NOSSO ARQUIVO NO LOCAL
from unicodedata import decimal

import pandas as pd
import re
print('pandas versao:', pd.__version__)
print('Bibliotecas importadas com sucesso!')

#Comando: Criamos uma variavel para que armazena nossa rota de acesso ao arquivo principal
PASTA= r'C:\Users\miran\OneDrive\Desktop\turma-visualizacao-de-dados\alunos\isaac_Trenard\semana_04_ANOTAÇÕES\base_rh.csv'
print('Base de dados carregada com sucesso!')


df= pd.read_csv(
    PASTA,
    sep=';',           
    encoding='cp1252',
    decimal=',' )
print('DF Decodificado com sucesso!')

pandas versao: 3.0.1
Bibliotecas importadas com sucesso!
Base de dados carregada com sucesso!
DF Decodificado com sucesso!

# Passo 2: diagnóstico

In [17]:
print(f'  Total de linhas  : {df.shape[0]}')
print(f'  Total de colunas : {df.shape[1]}')
print('\n Diagnostico de Tipos de dados de cada coluna')
df.info()
print('\n Encontramos que cada coluna tem os seguinte valores nulos') 
print('\n Dado faltante reprensentado= 1, e dado completo ou preenchido= 0')
print(f'\n{(df.isnull().sum())}')
print(f'\n Colunas do dataset:')
print(f'\n{df.columns.tolist()}')
print('\n Amostra dos dados:')
print('\n Primeiros dados na base de dados ')
df.head()

  Total de linhas  : 1000
  Total de colunas : 10

 Diagnostico de Tipos de dados de cada coluna
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Funcionario  1000 non-null   int64
 1   Nome            1000 non-null   str
 2   Departamento    1000 non-null   str
 3   Cargo           1000 non-null   str
 4   Salario         1000 non-null   float64
 5   Data_Admissao   1000 non-null   str
 6   Genero          1000 non-null   str
 7   Idade           1000 non-null   int64
 8   Estado_Civil    1000 non-null   str
 9   Status          1000 non-null   str
dtypes: float64(1), int64(2), str(7)
memory usage: 78.3 KB

 Encontramos que cada coluna tem os seguinte valores nulos

 Dado faltante reprensentado= 1, e dado completo ou preenchido= 0

ID_Funcionario    0
Nome              0
Departamento      0
Cargo             0
Salario           0
Data_Admissao     0
Genero            0
Idade             0
Estado_Civil      0
Status            0
dtype: int64

 Colunas do dataset:

['ID_Funcionario', 'Nome', 'Departamento', 'Cargo', 'Salario', 'Data_Admissao', 'Genero', 'Idade', 'Estado_Civil', 'Status']

 Amostra dos dados:

 Primeiros dados na base de dados

,ID_Funcionario,Nome,Departamento,Cargo,Salario,Data_Admissao,Genero,Idade,Estado_Civil,Status
0,1,Julia Nunes,Logística,Coordenador,9088.34,13/08/2024,F,43,Solteiro,Inativo
1,2,Sr. Gustavo Duarte,TI,Gerente,8155.98,29/04/2017,F,59,Solteiro,Inativo
2,3,Srta. Mariana Cunha,RH,Coordenador,14027.93,11/12/2024,F,27,Divorciado,Ativo
3,4,Ana Sophia da Cruz,Produção,Técnico,6647.97,16/06/2019,M,50,Casado,Inativo
4,5,Dr. Nicolas Pinto,Produção,Gerente,8730.19,29/03/2019,F,62,Casado,Inativo

# Passo 3: converter datas e criar colunas derivadas

In [18]:
from datetime import datetime, timedelta
data_str = '13/08/2024' 
data_objeto = datetime.strptime(data_str, '%d/%m/%Y')

print(f'Valor original da coluna DATA_ADMISSAO {data_str}')
print(f'Valor convertido da coluna DATA_ADMISSAO {data_objeto}')
print(f'Verificacao tipo de dado da coluna Data_Admissao {type(data_objeto)}')

print(f'Extrair elemento separado Ano : {data_objeto.year}')
print(f'Extrair elemento separado Mês : {data_objeto.month}')
print(f'Extrair elemento separado Dia : {data_objeto.day}')

print(f'Formato original da coluna Data Admissao {df['Data_Admissao']}.dtype')

df_ajustado = df.copy()
df_ajustado['Data_Admissao'] = pd.to_datetime(df_ajustado['Data_Admissao'], format='%d/%m/%Y', errors='coerce')
print(f'DATA DE ADMISSAO AJUSTADA PARA : {df_ajustado['Data_Admissao'].dtype}')
hoje = datetime.today ()
periodo_de_tempo = hoje - data_objeto

print(f'Data de admissão : {data_str}')
print(f'Hoje: {hoje.strftime("%d/%m/%Y")}')
print(f'Periodo de tempo: {periodo_de_tempo.days} dias')
print(f'Em anos: {periodo_de_tempo.days / 365.25:.1f} anos')

df_ajustado['Ano_Admissao'] = df_ajustado['Data_Admissao'].dt.year
df_ajustado['Mes_admissao'] = df_ajustado['Data_Admissao'].dt.month
df_ajustado['Trimestre'] = df_ajustado['Data_Admissao'].dt.quarter
df_ajustado['Tempo_na_empresa'] = ((hoje - df_ajustado['Data_Admissao']).dt.days/365.25 ).round(1)

df_ajustado.head()

Valor original da coluna DATA_ADMISSAO 13/08/2024
Valor convertido da coluna DATA_ADMISSAO 2024-08-13 00:00:00
Verificacao tipo de dado da coluna Data_Admissao <class 'datetime.datetime'>
Extrair elemento separado Ano : 2024
Extrair elemento separado Mês : 8
Extrair elemento separado Dia : 13
Formato original da coluna Data Admissao 0      13/08/2024
1      29/04/2017
2      11/12/2024
3      16/06/2019
4      29/03/2019
          ...
995    06/05/2022
996    05/06/2023
997    29/12/2023
998    25/12/2019
999    14/11/2022
Name: Data_Admissao, Length: 1000, dtype: str.dtype
DATA DE ADMISSAO AJUSTADA PARA : datetime64[us]
Data de admissão : 13/08/2024
Hoje: 24/05/2026
Periodo de tempo: 649 dias
Em anos: 1.8 anos

,ID_Funcionario,Nome,Departamento,Cargo,Salario,Data_Admissao,Genero,Idade,Estado_Civil,Status,Ano_Admissao,Mes_admissao,Trimestre,Tempo_na_empresa
0,1,Julia Nunes,Logística,Coordenador,9088.34,2024-08-13,F,43,Solteiro,Inativo,2024,8,3,1.8
1,2,Sr. Gustavo Duarte,TI,Gerente,8155.98,2017-04-29,F,59,Solteiro,Inativo,2017,4,2,9.1
2,3,Srta. Mariana Cunha,RH,Coordenador,14027.93,2024-12-11,F,27,Divorciado,Ativo,2024,12,4,1.4
3,4,Ana Sophia da Cruz,Produção,Técnico,6647.97,2019-06-16,M,50,Casado,Inativo,2019,6,2,6.9
4,5,Dr. Nicolas Pinto,Produção,Gerente,8730.19,2019-03-29,F,62,Casado,Inativo,2019,3,1,7.2

# Passo 4: groupby — maior e menor média de tempo de casa

In [19]:
media_cargo = df_ajustado.groupby('Cargo')['Tempo_na_empresa'].mean().round(1)
print('Tempo médio na empresa por cargo:')
print(media_cargo)

maior_media = media_cargo.idxmax()
menor_media = media_cargo.idxmin()
print(f'Tempo minimo por cargo na empresa {menor_media} - {media_cargo[maior_media]} anos')
print(f'Tempo maximo por cargo na empresa {maior_media}- {media_cargo[menor_media]} anos')

Tempo médio na empresa por cargo:
Cargo
Analista       5.9
Assistente     5.3
Coordenador    5.7
Gerente        5.2
Técnico        5.5
Name: Tempo_na_empresa, dtype: float64
Tempo minimo por cargo na empresa Gerente - 5.9 anos
Tempo maximo por cargo na empresa Analista- 5.2 anos

# Passo 5: exportar para Excel

In [25]:
df.to_excel('base_rh_PRONTA_EXERCICIO_SEMANA_4.xlsx', index=False, sheet_name='BASE DE DADOS')
print('Base de dados coletada, limpada, organizada e exportada! ')

Base de dados coletada, limpada, organizada e exportada!

# Passo 6: cole o output do git log aqui como comentário
# git log:

PS C:\Users\miran\OneDrive\Desktop\turma-visualizacao-de-dados> git log --author="isaaclicCode" --oneline
5e7120a (HEAD -> master, origin/master, origin/HEAD) avancos semana 4
ffd5d0c avancos
de8b4f8 exercicios semana 4 - analise de dados
7cff6ae  carregando exercicios semana 4
fb0d658 exercicios semana 3
deaac41 readme.md
2bab13a pratica
7aaea18 resumo e pratica
a3e7060 Sobre semana 3 praticas
14d314a Ajustes / aulas e rename
:...skipping...
5e7120a (HEAD -> master, origin/master, origin/HEAD) avancos semana 4
ffd5d0c avancos
de8b4f8 exercicios semana 4 - analise de dados
7cff6ae  carregando exercicios semana 4
fb0d658 exercicios semana 3
deaac41 readme.md
2bab13a pratica
7aaea18 resumo e pratica
a3e7060 Sobre semana 3 praticas
14d314a Ajustes / aulas e rename
a466ab7 Reestruturação pasta
: