**Aula_01 - Instalar as bibliotecas e carregar o csv.**

In [40]:
import pandas as pd
print(pd.__version__)

3.0.2

In [15]:
# Montar o Dataframe (df) carregando o arquivo de csv diretamente pela URL.

URL = (
    "https://raw.githubusercontent.com/"
    "cfneves/turma-visualizacao-de-dados/"
    "master/datasets/base_rh.csv"
)

# Carregar o csv com as configurações corretas para exibir os dados de forma integra.

# sep      → ponto-e-vírgula porque o TOTVS usa padrão europeu
# encoding → cp1252 é o encoding do Windows (suporta ã é ç ú ô)
# decimal  → vírgula como separador decimal

df = pd.read_csv(URL, 
    sep=";", 
    encoding="cp1252", 
    decimal=","
    )

In [29]:
# Conferência imediata — sempre faça isso após qualquer leitura

print(f"Shape: {df.shape}") #Mostra o número de linhas e colunas do DataFrame
print(f"\nTipos:\n{df.dtypes}") #Mostra os tipos de dados de cada coluna do DataFrame
print(f"\nPrimeiras 3 linhas:\n{df.head(3).to_string(index=False)}") #Mostra as primeiras 3 linhas do DataFrame sem os índices
print(f"\nÚltimas 5 linhas:\n{df.tail(5).to_string(index=False)}") #Mostra as últimas 5 linhas do DataFrame sem os índices

Shape: (1000, 10)

Tipos:
ID_Funcionario      int64
Nome                  str
Departamento          str
Cargo                 str
Salario           float64
Data_Admissao         str
Genero                str
Idade               int64
Estado_Civil          str
Status                str
dtype: object

Primeiras 3 linhas:
 ID_Funcionario                Nome Departamento       Cargo  Salario Data_Admissao Genero  Idade Estado_Civil  Status
              1         Julia Nunes    Logística Coordenador  9088.34    13/08/2024      F     43     Solteiro Inativo
              2  Sr. Gustavo Duarte           TI     Gerente  8155.98    29/04/2017      F     59     Solteiro Inativo
              3 Srta. Mariana Cunha           RH Coordenador 14027.93    11/12/2024      F     27   Divorciado   Ativo

Últimas 5 linhas:
 ID_Funcionario               Nome Departamento    Cargo  Salario Data_Admissao Genero  Idade Estado_Civil  Status
            996     Matheus Aragão   Financeiro Analista 11389.03    06/05/2022      F     26        Viúvo   Ativo
            997       Ryan Martins   Financeiro Analista 14060.42    05/06/2023      F     37        Viúvo   Ativo
            998  Isabelly Ferreira           TI  Gerente  2348.73    29/12/2023      F     58     Solteiro Inativo
            999      Thales Farias     Produção Analista  9430.62    25/12/2019      M     41     Solteiro   Ativo
           1000 Sra. Maysa Costela     Produção  Técnico 12549.72    14/11/2022      M     46        Viúvo Inativo

**Por que isso importa?**

Note que Salario já é float64 — isso significa que df["Salario"].mean() vai funcionar. 
Se esquecermos decimal=",", Salario vira object e a média retorna TypeError. 
Esse erro só aparece quando você tenta calcular — e já passou horas analisando o dado "errado" sem saber.

**Exploração básica do DataFrame — Antes de qualquer transformação**

Após qualquer leitura, o primeiro passo é sempre explorar o dado. Esses comandos são o "scanner" do analista — você nunca mexe num dado sem antes conhecê-lo. Execute cada um em uma célula separada no notebook para ver o resultado com clareza.

In [64]:
# Célula 2 — shape e colunas
# Dimensão do DataFrame: (Linhas e colunas)
print("Dimensão do DataFrame (linhas, colunas):\n")

print(f"Shape: {df.shape}")      #Mostra o número de linhas e colunas do DataFrame
print(f"Linhas: {df.shape[0]}")  #Mostra o número de linhas do DataFrame
print(f"Colunas: {df.shape[1]}") #Mostra o número de colunas do DataFrame
print(f"\nNomes das colunas:")   #Mosra o título "Nomes das colunas:"
print(df.columns.tolist())       #Mostra os nomes das colunas do DataFrame em formato de lista

Dimensão do DataFrame (linhas, colunas):

Shape: (1000, 10)
Linhas: 1000
Colunas: 10

Nomes das colunas:
['ID_Funcionario', 'Nome', 'Departamento', 'Cargo', 'Salario', 'Data_Admissao', 'Genero', 'Idade', 'Estado_Civil', 'Status']

In [63]:
# Célula 3 — Linha específica pelo índice
print("Linha específica pelo índice (exemplo: índice 3):\n")
df.iloc[3]

Linha específica pelo índice (exemplo: índice 3):

ID_Funcionario                     4
Nome              Ana Sophia da Cruz
Departamento                Produção
Cargo                        Técnico
Salario                      6647.97
Data_Admissao             16/06/2019
Genero                             M
Idade                             50
Estado_Civil                  Casado
Status                       Inativo
Name: 3, dtype: object

In [62]:
#  Célula 4 — tipos e nulos

# .info() — resumo completo: tipos, nulos e uso de memória
# É o comando mais importante para um primeiro diagnóstico
print("Resumo completo do DataFrame:\n")
df.info()

Resumo completo do DataFrame:

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID_Funcionario  1000 non-null   int64
 1   Nome            1000 non-null   str
 2   Departamento    1000 non-null   str
 3   Cargo           1000 non-null   str
 4   Salario         1000 non-null   float64
 5   Data_Admissao   1000 non-null   str
 6   Genero          1000 non-null   str
 7   Idade           1000 non-null   int64
 8   Estado_Civil    1000 non-null   str
 9   Status          1000 non-null   str
dtypes: float64(1), int64(2), str(7)
memory usage: 78.3 KB

In [67]:
# Quantidade de nulos por coluna
print("\nQuantidade de valores nulos por coluna:\n")
print("\nNulos por coluna:")
print(df.isnull().sum())

# Percentual de nulos — mais útil em bases grandes
print("\n% de nulos:")
print((df.isnull().sum() / len(df) * 100).round(2))

Quantidade de valores nulos por coluna:


Nulos por coluna:
ID_Funcionario    0
Nome              0
Departamento      0
Cargo             0
Salario           0
Data_Admissao     0
Genero            0
Idade             0
Estado_Civil      0
Status            0
dtype: int64

% de nulos:
ID_Funcionario    0.0
Nome              0.0
Departamento      0.0
Cargo             0.0
Salario           0.0
Data_Admissao     0.0
Genero            0.0
Idade             0.0
Estado_Civil      0.0
Status            0.0
dtype: float64

In [70]:
# Célula 5 — estatísticas numéricas

# .describe() — estatísticas das colunas numéricas
# count, mean, std, min, 25%, 50%, 75%, max
df.describe().round(2)

       ID_Funcionario   Salario    Idade
count         1000.00   1000.00  1000.00
mean           500.50   8579.95    41.40
std            288.82   3657.37    13.67
min              1.00   2000.71    18.00
25%            250.75   5564.54    30.00
50%            500.50   8571.13    41.00
75%            750.25  11554.63    53.00
max           1000.00  14954.51    65.00

In [83]:
# Célula 6 — cardinalidade e distribuição

# Valores únicos por coluna — identifica colunas categóricas
print("Valores únicos por coluna:\n")
print(df.nunique())

# Distribuição de cada coluna categórica relevante
for col in ("Departamento", "Cargo", "Genero", "Status", "Estado_Civil"):
    print(f"\n── {col} ──")
    print(df[col].value_counts())

Valores únicos por coluna:

ID_Funcionario    1000
Nome               976
Departamento         6
Cargo                5
Salario           1000
Data_Admissao      878
Genero               2
Idade               48
Estado_Civil         4
Status               2
dtype: int64

── Departamento ──
Departamento
Financeiro    189
Produção      182
RH            166
Vendas        160
Logística     156
TI            147
Name: count, dtype: int64

── Cargo ──
Cargo
Coordenador    225
Gerente        221
Assistente     199
Analista       178
Técnico        177
Name: count, dtype: int64

── Genero ──
Genero
F    510
M    490
Name: count, dtype: int64

── Status ──
Status
Ativo      515
Inativo    485
Name: count, dtype: int64

── Estado_Civil ──
Estado_Civil
Solteiro      265
Viúvo         261
Divorciado    240
Casado        234
Name: count, dtype: int64

In [93]:
# Célula 7 — seleção de colunas e filtros simples

# Selecionar uma coluna → Series
df["Nome"].head(3)

0            Julia Nunes
1     Sr. Gustavo Duarte
2    Srta. Mariana Cunha
Name: Nome, dtype: str

In [94]:
# Selecionar múltiplas colunas → DataFrame
df[["Nome", "Departamento", "Salario"]].head(4)

                  Nome Departamento   Salario
0          Julia Nunes    Logística   9088.34
1   Sr. Gustavo Duarte           TI   8155.98
2  Srta. Mariana Cunha           RH  14027.93
3   Ana Sophia da Cruz     Produção   6647.97

In [102]:
# Filtro simples: apenas funcionários Ativos
ativos = df[df["Status"] == "Ativo"]
inativos = df[df["Status"] == "Inativo"]
print(f"Ativos: {len(ativos)} | Inativos: {len(inativos)}")

Ativos: 515 | Inativos: 485

In [105]:
# Filtro composto: Gerentes do departamento de TI
gerentes_ti = df[(df["Cargo"] == "Gerente") & (df["Departamento"] == "TI")]
print(f"\nGerentes de TI:")
print(gerentes_ti[["Nome", "Salario", "Status"]].to_string(index=False))

Gerentes de TI:
                       Nome  Salario  Status
         Sr. Gustavo Duarte  8155.98 Inativo
          Benjamin da Costa  9766.01 Inativo
           Catarina Costela  9597.83 Inativo
              Laura Cardoso  7364.46 Inativo
              Maria Cardoso 12127.27 Inativo
          Ana Júlia Cardoso  8738.63   Ativo
                Ian Pereira  2395.32   Ativo
          Ana Clara Peixoto  7301.14   Ativo
             Augusto Santos  8237.80 Inativo
            Manuela Barbosa  7015.91   Ativo
           Antônio Oliveira  5273.24   Ativo
        Luiz Gustavo da Luz  2543.19 Inativo
               Stella Costa 11718.30   Ativo
              Bryan da Cruz 11790.21   Ativo
             Emilly Freitas  5147.62 Inativo
          Brenda Nascimento  5429.24   Ativo
                Sofia Sales  4941.24 Inativo
            Manuela Cardoso  5305.96 Inativo
        Luiz Henrique Souza  4398.17   Ativo
             Bruna da Cunha  3423.93 Inativo
               Alícia Porto  9547.18 Inativo
             Bianca da Cruz  7903.06 Inativo
Sra. Maria Fernanda Freitas  2686.67   Ativo
            Emanuelly Souza  8305.81 Inativo
              Olivia Moraes  3124.24 Inativo
              Bernardo Lima  6149.05   Ativo
       Sra. Caroline Araújo  6750.44 Inativo
          Ana Clara Moreira 14523.10   Ativo
                Luna Novaes  3106.49 Inativo
          Valentina Cardoso 10602.13   Ativo
          Isabelly Ferreira  2348.73 Inativo

In [114]:
# Estatísticas rápidas de uma coluna
print(f"\nSalário — média: R$ {df['Salario'].mean():,.2f}")
print(f"Salário — maior: R$ {df['Salario'].max():,.2f}")
print(f"Salário — menor: R$ {df['Salario'].min():,.2f}")

Salário — média: R$ 8,579.95
Salário — maior: R$ 14,954.51
Salário — menor: R$ 2,000.71

**Por que isso importa ?**

Esses 7 comandos — shape, head, tail, info, isnull, describe, nunique + value_counts — são o protocolo mínimo de qualquer analista antes de tocar nos dados. 
Em mercado, você nunca entrega uma análise sem ter rodado esses comandos primeiro: eles revelam nulos escondidos, tipos errados e distribuições inesperadas que invalidam qualquer conclusão posterior.

**Exportando para JSON — formato de APIs e sistemas modernos**

In [117]:
import pandas as pd
import json

# ── Exportar o DataFrame para JSON ───────────────────────────
# orient="records"   → cada linha vira um objeto JSON independente
# force_ascii=False  → mantém ã é ç sem escapar (\u00e3 etc.)
# indent=2           → arquivo legível por humanos
df.to_json(
    "base_rh.json",
    orient="records",
    force_ascii=False,
    indent=2
)

print("✓ base_rh.json gerado")

✓ base_rh.json gerado

In [118]:
# ── Lendo de volta para confirmar ────────────────────────────
df_json = pd.read_json("base_rh.json")
print(f"Linhas lidas do JSON: {len(df_json)}")

Linhas lidas do JSON: 1000

In [119]:
# ── Visualizar os 2 primeiros registros no formato JSON ───────
with open("base_rh.json", "r", encoding="utf-8") as f:
    amostra = json.load(f)
print("\nPrimeiros 2 registros no JSON:")
print(json.dumps(amostra[:2], ensure_ascii=False, indent=2))

Primeiros 2 registros no JSON:
[
  {
    "ID_Funcionario": 1,
    "Nome": "Julia Nunes",
    "Departamento": "Logística",
    "Cargo": "Coordenador",
    "Salario": 9088.34,
    "Data_Admissao": "13/08/2024",
    "Genero": "F",
    "Idade": 43,
    "Estado_Civil": "Solteiro",
    "Status": "Inativo"
  },
  {
    "ID_Funcionario": 2,
    "Nome": "Sr. Gustavo Duarte",
    "Departamento": "TI",
    "Cargo": "Gerente",
    "Salario": 8155.98,
    "Data_Admissao": "29/04/2017",
    "Genero": "F",
    "Idade": 59,
    "Estado_Civil": "Solteiro",
    "Status": "Inativo"
  }
]

**Por que isso importa?**

orient="records" gera o formato que APIs REST esperam — uma lista de objetos, não um objeto com arrays. force_ascii=False é essencial: sem ele, "Produção" vira "Produ\u00e7\u00e3o" no arquivo, o que quebra sistemas que não interpretam escape unicode. Em indústria, o JSON gerado aqui pode alimentar um dashboard web ou uma API interna do setor de RH.

**Exportando para Excel**

Relatório por departamento, uma aba por setor

In [120]:
# ── Exportação simples: tudo em uma aba ──────────────────────
df.to_excel("base_rh.xlsx", index=False, sheet_name="Funcionarios")
print("✓ base_rh.xlsx (aba única) gerado")

✓ base_rh.xlsx (aba única) gerado

In [ ]:
# ── Exportação avançada: uma aba por departamento ────────────
# ExcelWriter permite escrever múltiplas abas no mesmo arquivo
with pd.ExcelWriter("base_rh_por_depto.xlsx", engine="openpyxl") as writer:

    # Aba 1: dataset completo
    df.to_excel(writer, sheet_name="Todos", index=False)

    # Uma aba para cada departamento
    for depto in df["Departamento"].unique():
        df_depto = df[df["Departamento"] == depto]
        # Nome da aba limitado a 31 chars (limite do Excel)
        nome_aba = depto[:31]
        df_depto.to_excel(writer, sheet_name=nome_aba, index=False)
        print(f"  Aba '{nome_aba}': {len(df_depto)} registros")

print("\n✓ base_rh_por_depto.xlsx gerado")

  Aba 'Logística': 156 registros
  Aba 'TI': 147 registros
  Aba 'RH': 166 registros
  Aba 'Produção': 182 registros
  Aba 'Vendas': 160 registros
  Aba 'Financeiro': 189 registros

✓ base_rh_por_depto.xlsx gerado

Aba RH: 166 funcionários
               Nome       Cargo  Salario
Srta. Mariana Cunha Coordenador 14027.93
      Marcela Costa    Analista 12403.42
  Gabrielly Cardoso    Analista  2728.36
 Dr. Calebe Barbosa    Analista  3852.93

In [125]:
# ── Lendo de volta uma aba específica ────────────────────────
df_rh = pd.read_excel("base_rh_por_depto.xlsx", sheet_name="RH")
print(f"\nAba RH: {len(df_rh)} funcionários")
print(df_rh[["Nome", "Cargo", "Salario"]].head(4).to_string(index=False))

Aba RH: 166 funcionários
               Nome       Cargo  Salario
Srta. Mariana Cunha Coordenador 14027.93
      Marcela Costa    Analista 12403.42
  Gabrielly Cardoso    Analista  2728.36
 Dr. Calebe Barbosa    Analista  3852.93

**Por que isso importa?**

O ExcelWriter como gerenciador de contexto (with) garante que o arquivo seja fechado corretamente — sem isso o Excel fica corrompido. O limite de 31 caracteres no nome da aba é uma restrição do Excel, não do pandas: se ultrapassar, o arquivo abre com erro. Em projetos reais, relatórios assim são enviados automaticamente por e-mail para gestores — você vai ver isso no Power Automate na Semana de Automação.

**Módulo datetime — trabalhando com datas**

"Turma, a coluna Data_Admissao chegou como string. O pandas não sabe que '13/08/2024' é uma data — pra ele é só texto. Se a gente não converter, não consegue calcular há quantos anos alguém está na empresa, não consegue filtrar quem foi admitido nos últimos 2 anos, não consegue agrupar por trimestre. Data é dado, não texto. Vamos resolver isso agora."

Convertendo datas e calculando tempo de casa

In [127]:
import pandas as pd
print(pd.__version__)
from datetime import date, datetime, timedelta

3.0.2

In [133]:
# ── 1. Entendendo strptime e strftime (módulo datetime puro) ──
data_texto = "20/07/1982"

In [142]:
# strptime: converte string → objeto datetime
# %d = dia com zero à esquerda | %m = mês | %Y = ano 4 dígitos
data_obj = datetime.strptime(data_texto, "%d/%m/%Y")
print("Antes da conversão\n")
print(f"String original : {data_texto}")
print(f"Tipo original   : {type(data_texto)}\n")
print("Após conversão\n")
print(f"Objeto datetime : {data_obj}")
print(f"Tipo            : {type(data_obj)}")

Antes da conversão

String original : 20/07/1982
Tipo original   : <class 'str'>

Após conversão

Objeto datetime : 1982-07-20 00:00:00
Tipo            : <class 'datetime.datetime'>

In [136]:
# strftime: converte objeto datetime → string formatada
formatado = data_obj.strftime("%B de %Y")   # %B = nome do mês
print(f"Formatado: {formatado}")

Formatado: julho de 1982

In [147]:
# ── 2. timedelta: diferença entre datas ──────────────────────
hoje = datetime.today()
diferenca = hoje - data_obj          # resultado é um timedelta
print(f"\nHoje       : {hoje.strftime('%d/%m/%Y')}")
print(f"Diferença  : {diferenca.days} dias")
print(f"Em anos    : {diferenca.days / 365.25:.1f} anos")

Hoje       : 17/05/2026
Diferença  : 16007 dias
Em anos    : 43.8 anos

In [149]:
# ── 3. Aplicando no DataFrame inteiro ────────────────────────
# pd.to_datetime converte a coluna inteira — muito mais eficiente
# do que aplicar strptime linha a linha com .apply()
df["Data_Admissao"] = pd.to_datetime(
    df["Data_Admissao"],
    format="%d/%m/%Y",
    errors="coerce"   # datas inválidas → NaT (não quebra o pipeline)
)

print(f"\nTipo após conversão: {df['Data_Admissao'].dtype}")
print(f"Valores NaT gerados: {df['Data_Admissao'].isna().sum()}")

Tipo após conversão: datetime64[us]
Valores NaT gerados: 0

In [153]:
# ── 4. Coluna de tempo de casa em anos ───────────────────────
hoje_ts = pd.Timestamp.today()
df["Tempo_Casa_Anos"] = (
    (hoje_ts - df["Data_Admissao"]).dt.days / 365.25
).round(1)

# ── 5. Resultado ─────────────────────────────────────────────
print("\nAmostra — Data convertida e tempo de casa:")
cols = ["Nome", "Data_Admissao", "Tempo_Casa_Anos"]
print(df[cols].head(6).to_string(index=False))

Amostra — Data convertida e tempo de casa:
               Nome Data_Admissao  Tempo_Casa_Anos
        Julia Nunes    2024-08-13              1.8
 Sr. Gustavo Duarte    2017-04-29              9.0
Srta. Mariana Cunha    2024-12-11              1.4
 Ana Sophia da Cruz    2019-06-16              6.9
  Dr. Nicolas Pinto    2019-03-29              7.1
      Marcela Costa    2024-07-23              1.8

**Colunas derivadas de data + filtros por período**

Com a data convertida, extraímos atributos e aplicamos filtros — as operações mais pedidas em relatórios de RH industrial: headcount por ano de admissão, veteranos na empresa, admissões nos últimos 12 meses.

In [155]:
# ── 1. Extraindo componentes da data com .dt ─────────────────
# .dt é o acessor de datetime no pandas — dá acesso a ano, mês, etc.
df["Ano_Admissao"]  = df["Data_Admissao"].dt.year
df["Mes_Admissao"]  = df["Data_Admissao"].dt.month
df["Dia_Semana"]    = df["Data_Admissao"].dt.day_name()   # nome do dia
df["Trimestre"]     = df["Data_Admissao"].dt.quarter

print("Colunas derivadas criadas:")
cols = ["Nome", "Data_Admissao", "Ano_Admissao", "Mes_Admissao", "Trimestre"]
print(df[cols].head(4).to_string(index=False))

Colunas derivadas criadas:
               Nome Data_Admissao  Ano_Admissao  Mes_Admissao  Trimestre
        Julia Nunes    2024-08-13          2024             8          3
 Sr. Gustavo Duarte    2017-04-29          2017             4          2
Srta. Mariana Cunha    2024-12-11          2024            12          4
 Ana Sophia da Cruz    2019-06-16          2019             6          2

In [156]:
# ── 2. Faixa de tempo de casa (coluna categórica) ─────────────
def classificar_tempo(anos):
    if anos < 1:
        return "Menos de 1 ano"
    elif anos < 3:
        return "1 a 3 anos"
    elif anos < 5:
        return "3 a 5 anos"
    else:
        return "Mais de 5 anos"

df["Faixa_Tempo_Casa"] = df["Tempo_Casa_Anos"].apply(classificar_tempo)

print("\nDistribuição por faixa de tempo de casa:")
print(df["Faixa_Tempo_Casa"].value_counts().to_string())

Distribuição por faixa de tempo de casa:
Faixa_Tempo_Casa
Mais de 5 anos    542
1 a 3 anos        213
3 a 5 anos        213
Menos de 1 ano     32

In [159]:
# ── 3. Filtros por período ────────────────────────────────────
hoje  = pd.Timestamp.today()
um_ano_atras = hoje - pd.DateOffset(years=1)
cinco_anos_atras = hoje - pd.DateOffset(years=5)

# Admitidos nos últimos 12 meses
novos = df[df["Data_Admissao"] >= um_ano_atras]

# Veteranos — mais de 5 anos de casa
veteranos = df[df["Data_Admissao"] < cinco_anos_atras]

print(f"\nAdmitidos nos últimos 12 meses : {len(novos)} funcionários")
print(f"Veteranos (5+ anos de casa)    : {len(veteranos)} funcionários")

# ── 4. Admissões por ano — panorama histórico ─────────────────
print("\nAdmissões por ano:")
print(
    df.groupby("Ano_Admissao")
    .size()
    .rename("Admissoes")
    .sort_index()
    .to_string()
)

# ── 5. Salário médio dos veteranos vs novos ───────────────────
print("\nSalário médio:")
print(f"  Novos (últimos 12 meses): R$ {novos['Salario'].mean():,.2f}")
print(f"  Veteranos (5+ anos)     : R$ {veteranos['Salario'].mean():,.2f}")

Admitidos nos últimos 12 meses : 35 funcionários
Veteranos (5+ anos de casa)    : 535 funcionários

Admissões por ano:
Ano_Admissao
2015     33
2016     87
2017     99
2018     89
2019    101
2020     94
2021     94
2022    108
2023    106
2024    113
2025     76

Salário médio:
  Novos (últimos 12 meses): R$ 8,900.48
  Veteranos (5+ anos)     : R$ 8,605.53

**Por que isso importa?**

pd.DateOffset(years=1) é mais correto que pd.Timedelta(days=365) para filtros de "último ano" — ele considera anos bissextos e meses com 28/30/31 dias. O insight do salário médio (veteranos ganham mais) é exatamente o tipo de análise que o gestor de RH vai pedir: "quem ficou ganhou mais com o tempo?" — e você responde com três linhas de código.